### ISSUE TITLE
Teleport to Airport E46 XP 11

### ISSUE THREAD

**Issue by VitoJackson** [skiselkov/X-RAAS2#2]
Hi,

When i fly from Frankfurt to Munich EDDF-EDDM on the descent than i was Teleportet to the Airport
E46. 

i think its a Issuse of X-RAAS 2.1B2

[Log.txt](https://github.com/skiselkov/X-RAAS2/files/1252467/Log.txt)

**Comment by skiselkov** [comment]
I kind of doubt it's a bug in X-RAAS, since X-RAAS has no ability to modify the aircraft's position. The position is only ever read, but never written. Are you sure you've not tried to change some flight parameter in the Flight menu and accidentally X-Plane picked up a random location change or something?

**Comment by VitoJackson** [comment]
Hi Skiselkov,

Teleportation was triggered by SmartCopilot.

Thx for Help

**Comment by skiselkov** [comment]
Thanks for helping in getting this sorted out!
